// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace bharathome_api.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20260505223530_AddSchemaChangeFields")]
    partial class AddSchemaChangeFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("ListingsCount")
                        .HasColumnType("integer")
                        .HasColumnName("listings_count");

                    b.Property<string>("OperatingLocation")
                        .HasColumnType("text")
                        .HasColumnName("operating_location");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<string>("ReraRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rera_registration_number");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Property", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("Baths")
                        .HasColumnType("integer")
                        .HasColumnName("baths");

                    b.Property<int>("Beds")
                        .HasColumnType("integer")
                        .HasColumnName("beds");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ExpresswayProximity")
                        .HasColumnType("boolean")
                        .HasColumnName("expressway_proximity");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<bool>("IsReraRegistered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rera_registered");

                    b.Property<string>("ListerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lister_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("ReraRegistrationNumber")
                        .HasColumnType("text")
                        .HasColumnName("rera_registration_number");

                    b.Property<int>("Sqft")
                        .HasColumnType("integer")
                        .HasColumnName("sqft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("VastuOrientation")
                        .HasColumnType("text")
                        .HasColumnName("vastu_orientation");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("PropertyAgent", b =>
                {
                    b.Property<string>("PropertyId")
                        .HasColumnType("text")
                        .HasColumnName("property_id");

                    b.Property<string>("AgentId")
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.HasKey("PropertyId", "AgentId")
                        .HasName("pk_property_agents");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_property_agents_agent_id");

                    b.ToTable("property_agents", (string)null);
                });

            modelBuilder.Entity("PropertyAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_id");

                    b.HasKey("Id")
                        .HasName("pk_property_amenities");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_property_amenities_property_id");

                    b.ToTable("property_amenities", (string)null);
                });

            modelBuilder.Entity("PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_property_images");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_property_images_property_id");

                    b.ToTable("property_images", (string)null);
                });

            modelBuilder.Entity("TestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_test_items");

                    b.ToTable("test_items", (string)null);
                });

            modelBuilder.Entity("UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("AccountStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("account_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<string>("KycDocumentUrl")
                        .HasColumnType("text")
                        .HasColumnName("kyc_document_url");

                    b.Property<string>("KycRejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("kyc_rejection_reason");

                    b.Property<int>("KycStatus")
                        .HasColumnType("integer")
                        .HasColumnName("kyc_status");

                    b.Property<DateTime?>("KycSubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kyc_submitted_at");

                    b.Property<DateTime?>("KycVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kyc_verified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("PropertiesListed")
                        .HasColumnType("integer")
                        .HasColumnName("properties_listed");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<DateTime?>("SubscriptionExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_expiry");

                    b.Property<string>("UserPhoto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_photo");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Agent", b =>
                {
                    b.HasOne("UserProfile", "UserProfile")
                        .WithOne("Agent")
                        .HasForeignKey("Agent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agents_user_profiles_id");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("PropertyAgent", b =>
                {
                    b.HasOne("Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_agents_agents_agent_id");

                    b.HasOne("Property", "Property")
                        .WithMany("PropertyAgents")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_agents_properties_property_id");

                    b.Navigation("Agent");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyAmenity", b =>
                {
                    b.HasOne("Property", "Property")
                        .WithMany("Amenities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_amenities_properties_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyImage", b =>
                {
                    b.HasOne("Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_images_properties_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Property", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Images");

                    b.Navigation("PropertyAgents");
                });

            modelBuilder.Entity("UserProfile", b =>
                {
                    b.Navigation("Agent");
                });
#pragma warning restore 612, 618
        }
    }
}
